version: 2
updates:
  # Enable version updates for npm (JavaScript SDK)
  - package-ecosystem: "npm"
    directory: "/packages/nexusevent-js"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "i-vox"
    assignees:
      - "i-vox"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for pub (Flutter SDK)
  - package-ecosystem: "pub"
    directory: "/packages/nexusevent_flutter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "i-vox"
    assignees:
      - "i-vox"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "i-vox"
    assignees:
      - "i-vox"