blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/i-vox/NexusEvent/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issue
    url: mailto:i.flint.lab@gmail.com
    about: Report security vulnerabilities privately